language: cpp
dist: trusty

notifications:
    email: false

cache:
    - apt
    - ccache

git:
    depth: 3

addons:
    apt:
        sources:
            - sourceline: ppa:beineri/opt-qt571-trusty
        packages:
            - qt57base
            - zlib1g-dev
            - libosmesa6-dev
            - libssl-dev
            - libqwt-dev
            - libfreetype6-dev
            - libftgl-dev

env:
    global:
        - OMP_NUM_THREADS=4

before_install:
    - source /opt/qt57/bin/qt57-env.sh
    - mkdir ../build
    - cd ../build

script:
    - cmake -D CMAKE_CXX_FLAGS="-Wno-narrowing" -D CMAKE_BUILD_TYPE=Release -D WORKBENCH_MESA_DIR=/usr ../workbench/src
    - make -j 4
    - ctest
